#!/usr/bin/env python3
"""Build the self-contained Python runtime committed with the portable skill."""
from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills" / "ontology-graph-builder"
ENGINE_SOURCE = ROOT / "ontology_graph_cli"
ENGINE_DESTINATION = SKILL / "scripts" / "engine" / "ontology_graph_cli"
MODULES = ("__init__.py", "core.py", "prd.py", "cli.py")
HEADER = "# Generated by scripts/build-standalone-skill.py. Edit ontology_graph_cli instead.\n"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> Path:
    if ENGINE_DESTINATION.parent.exists():
        shutil.rmtree(ENGINE_DESTINATION.parent)
    ENGINE_DESTINATION.mkdir(parents=True)
    checksums = {}
    for name in MODULES:
        source, destination = ENGINE_SOURCE / name, ENGINE_DESTINATION / name
        destination.write_bytes(HEADER.encode() + source.read_bytes())
        checksums[name] = digest(source)
    manifest = {"schema_version": 1, "package": "ontology-graph-cli", "version": "0.1.0", "modules": checksums}
    target = SKILL / "scripts" / "bundle_manifest.json"
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    shutil.copyfile(ROOT / "LICENSE", SKILL / "LICENSE")
    return target


if __name__ == "__main__": print(build())
